config/routes.rb
Contestrus::Application.routes.draw do
  root "sessions#new"

  resource :sessions

  resources :competitions do
    member do
      get "leaderboard" => "competitions#leaderboard"
    end
  end
  
  resources :users

  resources :tasks do
    resources :submissions
  end

  get '/instructions' => 'pages#instructions', as: 'instructions'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :competition
  has_many :groups, class_name: TestGroup
  has_many :test_cases
  has_many :submissions

  serialize :restrictions, Hash

  def self.solved
    joins(:submissions).where(:submissions => { status: ["Passed", "Partial"] })
  end

  def passed?(user)
    user.submissions.where(task_id: self.id, status: ["Passed", "Partial"]).any?
  end

  def points
    groups.sum(:points)
  end

  # Returns the number of distinct users who've solved a certain task.
  def times_solved
    User.all.inject(0) { |sum, user| sum + (self.passed?(user) ? 1 : 0) }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :visible_contest, except: [:index]

  def index
    @tasks = Task.all
  end

  def show
    @task        = Task.find(params[:id])
    @submission  = Submission.new(task_id: @task.id, user_id: params[:user_id])
    @submissions = current_user.submissions.where(task_id: @task.id).order("id DESC")
  end

  private
  def visible_contest
    unless Task.find(params[:id]).competition.visible?
      render :nothing => true, status: 403
      return false
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def submission_class(submission)
    case submission_status(submission)
    when "Pending"
      "info"
    when "Partial"
      "warning"
    when "Passed"
      "success"
    when "Failed"
      "error"
    end
  end

  def row_class(evaluation)
    case evaluation[:status]
    when "Correct"
      "success"
    else
      "error"
    end
  end

  def submission_status(submission)
    if pending?(submission)
      "Pending"
    elsif submission.completed?
      "Passed"
    elsif submission.partial?
      "Partial"
    else
      "Failed"
    end
  end

  def pending?(submission)
    submission.status == "Pending"
  end

  def evaluation_time(task)
    test_cases = task.test_cases.count
    distance_of_time_in_words(test_cases * task.restrictions["time"])
  end
end

app/views/tasks/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Solved #</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <% if task.competition.visible? %>
        <tr class="<%= current_user.submissions.for_task(task).passed.any? && "success" %>">
          <td><%= link_to task.name, task_path(task) %></td>
          <td><%= task.times_solved %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/show.html.erb
<% if @submission && @submission.errors.full_messages.size > 0 %>
  <div class="row-fluid">
    <div class="span12">
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <ul>
          <% @submission.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<h2><%= @task.name %></h2>
<p><%= render_markdown(@task.body) %></p>

<h3>Restrictions</h3>

<ul>
  <li>Memory limit: <%= number_to_human_size(@task.restrictions["memory"]) %></li>
  <li>Time limit: <%= @task.restrictions["time"] %>s</li>
  <li>Approximate worst case evaluation time: <%= evaluation_time(@task) %>
</ul>

<%= form_for @submission, url: task_submissions_path(@task.id), method: :post do |f| %>
  <%= f.hidden_field :task_id, value: @task.id %>
  <div class="control-group">
    <div class="controls">
      <%= f.file_field :source %>

      <div class="input-append">
        <input class="browser input-large uneditable-input" id="pretty_file" type="text"/>
        <a class="browser btn">Browse</a>
        <%= f.button "Evaluate", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<% unless @submissions.empty? %>
  <table class="table table-hover results">
    <thead>
      <tr>
        <th>#</th>
        <th>Submission time</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @submissions.each do |submission| %>
        <tr class="<%= submission_class(submission) %> accordion-toggle" data-toggle="collapse" data-target="#evaluations-<%= submission.id %>">
          <td><%= submission.id %></td>
          <td><%= submission.created_at.to_formatted_s(:short) %></td>

          <% if pending?(submission) %>
            <td>Pending</td>
          <% else %>
            <td>
              <%= submission.status %>
              (<%= submission.points %>)
            </td>
          <% end %>
        </tr>
        <% unless pending?(submission) %>
        <tr>
        <% if submission.status == "Build failed" %>
          <td colspan="6" style="padding: 0 !important">
            <pre>
              <%= submission.body %>
            </pre>
          </td>
        <% else %>
          <td colspan="6" style="padding: 0 !important">
            <div class="accordian-body collapse" id="evaluations-<%= submission.id %>">
              <table class="table table-condensed evaluation">
                <thead>
                  <th>#</th>
                  <th>Group #</th>
                  <th>Status</th>
                  <th>Duration</th>
                  <th>Input</th>
                  <th>Output</th>
                  <th>Expected</th>
                </thead>
                <tbody>
                <% i = 0 %>
                <% submission.body.each do |group_id, result| %>
                  <% result.each do |eval| %>
                    <% test_case = ::TestCase.find(eval[:test_case_id]) %>
                    <tr class="<%= row_class(eval) %>">
                      <td><%= i += 1 %></td>
                      <td><%= test_case.group_id %></td>
                      <td><%= eval[:status].humanize %></td>
                      <td><%= eval[:duration] && "#{eval[:duration].round(3)}s" %></td>
                      <td><pre><%= test_case.input.truncate(200) %></pre></td>
                      <td><pre><%= eval[:output].try(:truncate, 200) %></pre></td>
                      <td><pre><%= test_case.output.truncate(200) %></pre></td>
                    </tr>
                  <% end %>
                <% end %>
                </tbody>
              </table>
            </div>
          </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>