config/routes.rb
Contestrus::Application.routes.draw do
  root "sessions#new"

  resource :sessions

  resources :competitions do
    member do
      get "leaderboard" => "competitions#leaderboard"
    end
  end
  
  resources :users

  resources :tasks do
    resources :submissions
  end

  get '/instructions' => 'pages#instructions', as: 'instructions'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [['$','$'], ['\\(','\\)']]
        }
      });
    </script>

    <script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>

    <title>Contestrus</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3" id="sidebar">
          <ul class="nav nav-list">
            <% if current_user %>
              <li><%= link_to "My profile", user_path(current_user) %></li>
              <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
              <li><%= link_to "Tasks", tasks_path %></li>
            <% end %>

            <li><%= link_to "Instructions", instructions_path %></li>

            <% if current_user %>
              <% Competition.all.includes(:tasks).each do |competition| %>
                <li class="nav-header">
                  <% if competition.expired? %>
                    <%= link_to leaderboard_competition_path(competition) do %>
                      <%= competition.name %>
                      <%= time_left_badge(competition) %>
                    <% end %>
                  <% else %>
                    <%= competition.name %>
                    <%= time_left_badge(competition) %>
                  <% end %>
                </li>
                <% if competition.visible? %>
                  <% competition.tasks.each do |task| %>
                    <li>
                      <%= link_to task_path(task) do %>
                        <%= task.name %> <%= task_status_badge(task) %>
                        <%= task_points_badge(task, current_user) %>
                      <% end %>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>

        <div class="span9">
          <% if flash[:error] %>
            <div class="row-fluid">
              <div class="span12">
                <div class="alert alert-dismissable alert-danger">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <%= flash[:error] %>
                </div>
              </div>
            </div>
          <% end %>

          <% if flash[:notice] %>
            <div class="row-fluid">
              <div class="span12">
                <div class="alert alert-dismissable alert-notice">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <%= flash[:notice] %>
                </div>
              </div>
            </div>
          <% end %>

          <div class="row-fluid" id="content">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if ENV['PUSHER'] && current_user.try(:username) %>
    <script src="https://d3dy5gmtp8yhk7.cloudfront.net/2.1/pusher.min.js" type="text/javascript"></script>
    <script>
    var pusher = new Pusher('<%= ENV['PUSHER_KEY'] %>');
    var channel = pusher.subscribe('<%= ENV['PUSHER_PREFIX'] + current_user.username %>');
    channel.bind('submission_judged', function(data) {
        window.location.reload();
    });
    </script>
    <% end %>
  </body>
</html>